### PR TITLE
Force backlight off after taking a photo

### PR DESCRIPTION
**Pull request by kaytat**
This is specifically tested on the SD630.

### CODE REVIEW

**Comment by waterwingz** [comment]
kaytat : I forgot to ask this - did you disable "Image Review" mode in the Canon menu?  If not, that will turn the backlight back on after each shot.

**Comment by kaytat** [comment]
Yeah, and I confirmed that the setting works ok in regular, non-script running mode; as soon as I take a photo, the camera goes back into shooting mode and the review is bypassed.

**Comment by kaytat** [comment]
Another data point here is that this camera (SD630) seems to only respond to the backlight off setting and not the display off setting.

I tested this behavior with the "battery intervalometer" script.

I'm not sure what the difference is.

**Comment by waterwingz** [comment]
strange about set_LCD_display( ) not working - it's implemented correctly in the CHDK source and the address is uses is found by the sigfinder - which is pretty much always correct for stuff like that

**Comment by waterwingz** [comment]
try this :  (from https://chdk.setepontos.com/index.php?topic=12452.msg123428#msg123428 )
--[[
@title set_LCD test
--]]
props=require("propcase")

function restore_display()
    local disp = get_prop(props.DISPLAY_MODE)
    local clicks=0
    repeat
        click("display")
        clicks=clicks+1
        sleep(500)
    until (( disp == get_prop(props.DISPLAY_MODE)) or (clicks> 5))
end

sleep(1000)
print("Disabling Display")
sleep(1000)
set_lcd_display(0)
sleep(2000)
set_lcd_display(1)
print("Restored Display")
restore_display()
sleep(1000)

**Comment by kaytat** [comment]
The battery script quoted above works as expected.  The battery script linked from the wiki page doesn't use set_lcd_display.  The display option in that script seems to test the display key.

So I set the display mode to "LCD" and it works as expected.  After the 60s initial on-time, the LCD turns off and remains off.

I don't think it's work keeping change and so I'm closing this pull request.

**Comment by kaytat** [comment]
Actually,  can I request that the battery script be added to github and then I'd like to add the set_lcd_display function as an option to that script.

**Comment by waterwingz** [comment]
I'm looking at _git svn_ right now to see how hard it will be to move all my supported svn based scripts with history (there are about 20) to git.  Might take a week or so but seems possible.

**Comment by kaytat** [comment]
Sounds good.  Thanks for the input.  I'll be checking your projects periodically.

**Pull request closed without merging**
